# Generated by Django 4.2.11 on 2024-04-16 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_viewprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='viewprofile',
            old_name='Profile',
            new_name='profile',
        ),
        migrations.AlterUniqueTogether(
            name='viewprofile',
            unique_together={('employer', 'profile')},
        ),
    ]
