# Generated by Django 4.2.11 on 2024-04-16 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_alter_job_exp_level_employeejobs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeejobs',
            name='status',
            field=models.CharField(choices=[('Applied', 'applied'), ('Not Selected', 'not-selected'), ('Accepted', 'accepted'), ('Viewed', 'viewed')], default='applied', max_length=15),
        ),
    ]
