# Generated by Django 4.2.11 on 2024-04-16 19:16

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('job', '0004_alter_employeejobs_status'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='employeejobs',
            unique_together={('employee', 'job')},
        ),
    ]
